// <copyright file="BuilderHeader.Generator.cs" company="Adriaan Jacobus van Rensburg a.k.a Billy">
//     Copyright (c) Adriaan Jacobus van Rensburg a.k.a Billy. All rights reserved.
// </copyright>
// <license>
//     This source code is licensed under the MIT license found in the
//     LICENSE file in the root directory of this source tree.
// </license>
// <author>Adriaan Jacobus van Rensburg a.k.a Billy</author>
// <summary>FluentBuilder source generator implementation.</summary>

using FluentBuilder.Generator.Pools;
using System;
using System.Text;

namespace FluentBuilder.Generator.Generator
{
    internal static class BuilderHeaderGenerator
    {
        public static void GenerateHeader(StringBuilder sb)
        {
            var assembly = System.Reflection.Assembly.GetExecutingAssembly();
            var version = assembly.GetName().Version?.ToString() ?? "1.0.0";
            var timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//   Generated by: FluentBuilder.Generator v{version}");
            sb.AppendLine($"//   Generated on: {timestamp}");
            sb.AppendLine("//   Copyright © 2026 Adriaan Jacobus van Rensburg a.k.a Billy");
            sb.AppendLine($"//                  <billy.van.rensburg2@gmail.com>");
            sb.AppendLine("//");
            sb.AppendLine("//               DO NOT EDIT - changes will be overwritten");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
        }

        public static string GetHeader()
        {
            using var rented = StringBuilderPool.Rent();
            var sb = rented.Builder;
            GenerateHeader(sb);
            return sb.ToString();
        }
    }
}